import { readFileSync } from "node:fs";
import { mkdir, writeFile, rename } from "node:fs/promises";
import { join } from "node:path";
import type { SurahData } from "../src/types/quran";
export type Library = { surahs: SurahData[] };
export function readLibraryData(dataDir = "src/data"): Library {
  const manifest = JSON.parse(readFileSync(join(dataDir, "quran-library.json"), "utf8"));
  if (!manifest.format) return manifest as Library;
  if (manifest.format !== "surah-shards-v1" || !Array.isArray(manifest.shards))
    throw new Error("Unknown Quran library format");
  const seen = new Set<number>();
  const surahs = manifest.shards.map((entry: { number: number; file: string }) => {
    if (!Number.isInteger(entry.number) || entry.number < 1 || entry.number > 114 ||
        entry.file !== `quran-surahs/${String(entry.number).padStart(3, "0")}.json` || seen.has(entry.number))
      throw new Error("Invalid Quran library shard");
    seen.add(entry.number);
    const data = JSON.parse(readFileSync(join(dataDir, entry.file), "utf8")) as SurahData;
    if (data.surah.number !== entry.number || !Array.isArray(data.ayahs))
      throw new Error("Quran library shard mismatch");
    return data;
  });
  return { surahs };
}
async function atomic(path: string, text: string) {
  await writeFile(path + ".tmp", text);
  await rename(path + ".tmp", path);
}
export async function writeLibraryData(library: Library, dataDir = "src/data") {
  await mkdir(join(dataDir, "quran-surahs"), { recursive: true });
  const surahs = [...library.surahs].sort((a, b) => a.surah.number - b.surah.number);
  const shards = surahs.map((s) => ({ number: s.surah.number, file: `quran-surahs/${String(s.surah.number).padStart(3, "0")}.json` }));
  for (let i = 0; i < shards.length; i++)
    await atomic(join(dataDir, shards[i].file), JSON.stringify(surahs[i]) + "\n");
  const imports = shards.map((s) => `import surah${s.number} from "./${s.file}";`).join("\n");
  await atomic(join(dataDir, "quran-library.ts"), `// Generated by scripts/library-data.ts. Do not edit manually.\n${imports}\nconst library = { surahs: [${shards.map((s) => `surah${s.number}`).join(", ")}] };\nexport default library;\n`);
  await atomic(join(dataDir, "quran-library.json"), JSON.stringify({ format: "surah-shards-v1", shards }, null, 2) + "\n");
}
